Document: mando
Title: Debian mando Manual
Author: <insert document author here>
Abstract: This manual describes what mando is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mando/mando.sgml.gz

Format: postscript
Files: /usr/share/doc/mando/mando.ps.gz

Format: text
Files: /usr/share/doc/mando/mando.text.gz

Format: HTML
Index: /usr/share/doc/mando/html/index.html
Files: /usr/share/doc/mando/html/*.html
